"""Add content to Comment model

Revision ID: 0c688b8c2bc0
Revises: d4d9a0b28ab5
Create Date: 2025-07-23 00:24:30.384759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c688b8c2bc0'
down_revision: Union[str, None] = 'd4d9a0b28ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
