"""Add location column

Revision ID: 1c88b1922e43
Revises: 2fc498a09dbc
Create Date: 2025-07-23 09:28:01.121861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c88b1922e43'
down_revision: Union[str, None] = '2fc498a09dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('location', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'location')
    # ### end Alembic commands ###
