"""Add notification model

Revision ID: 333c5741d125
Revises: d077ea3eece1
Create Date: 2025-07-24 13:05:49.226876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333c5741d125'
down_revision: Union[str, None] = 'd077ea3eece1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'report_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'report_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
