"""change is_verified to true

Revision ID: 897e6a161d5c
Revises: c8d96bfa0da0
Create Date: 2025-07-30 14:52:07.647379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897e6a161d5c'
down_revision: Union[str, None] = 'c8d96bfa0da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
