"""Ensure UUID and datetime defaults for notifications

Revision ID: bc325bb5b8b5
Revises: 021575287e7c
Create Date: 2025-07-25 08:57:38.737889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc325bb5b8b5'
down_revision: Union[str, None] = '021575287e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
